minimumReleaseAgeExclude:
  - '@triggerix/core'
  - '@triggerix/editor'
  - '@triggerix/runtime'
  - triggerix-editor-vue
  - triggerix-editor-preset-war3
  - '@triggerix/registry'

shellEmulator: true

trustPolicy: no-downgrade

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
catalog:
  '@triggerix/runtime': ^0.0.7
  '@unocss/reset': latest
  '@vitejs/plugin-vue': ^6.0.7
  triggerix-editor-vue: ^0.0.8
  triggerix-editor-preset-war3: ^0.0.6
  typescript: ~6.0.3
  unocss: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.38
  vue-router: ^5.1.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
