/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type { _ExtractParamParserType } from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>
    '/demo/button-click': RouteRecordInfo<
      '/demo/button-click',
      '/demo/button-click',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/demo/button-modify-input': RouteRecordInfo<
      '/demo/button-modify-input',
      '/demo/button-modify-input',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/demo/carousel-linkage': RouteRecordInfo<
      '/demo/carousel-linkage',
      '/demo/carousel-linkage',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/demo/carousel-switch': RouteRecordInfo<
      '/demo/carousel-switch',
      '/demo/carousel-switch',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/demo/input-focus': RouteRecordInfo<
      '/demo/input-focus',
      '/demo/input-focus',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
      pathParamNames: never
    }
    'src/pages/demo/button-click.vue': {
      routes: '/demo/button-click'
      views: never
      pathParamNames: never
    }
    'src/pages/demo/button-modify-input.vue': {
      routes: '/demo/button-modify-input'
      views: never
      pathParamNames: never
    }
    'src/pages/demo/carousel-linkage.vue': {
      routes: '/demo/carousel-linkage'
      views: never
      pathParamNames: never
    }
    'src/pages/demo/carousel-switch.vue': {
      routes: '/demo/carousel-switch'
      views: never
      pathParamNames: never
    }
    'src/pages/demo/input-focus.vue': {
      routes: '/demo/input-focus'
      views: never
      pathParamNames: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
